# X auth_token
x_auth_token:

# X ct0 一般不需要自己获取
x_ct0:

# Pixiv refresh token
pixiv_refresh_token:

# JM Cookie
jm_cookie:

# Ehentai Cookie
ehentai_cookie:

# jinjiang Cookie
jinjiang_cookie:

# 12306 Cookie
a12306_cookie: JSESSIONID=123A08474DB447F2B3FAF3220061D96E; guidesStatus=off; highContrastMode=defaltMode; cursorStatus=off; _jc_save_fromStation=%u5317%u4EAC%2CBJP; _jc_save_toStation=%u4E0A%u6D77%2CSHH; _jc_save_wfdc_flag=dc; BIGipServerpassport=803733770.50215.0000; route=9036359bb8a8a461c164a04f8f50b252; _jc_save_fromDate=2025-04-29; _jc_save_toDate=2025-04-29; BIGipServerotn=1859715338.64545.0000
